/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_minipos_device_SerialPort */

#ifndef _Included_com_minipos_device_SerialPort
#define _Included_com_minipos_device_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
#undef com_minipos_device_SerialPort_PARITY_NONE
#define com_minipos_device_SerialPort_PARITY_NONE 0L
#undef com_minipos_device_SerialPort_PARITY_ODD
#define com_minipos_device_SerialPort_PARITY_ODD 1L
#undef com_minipos_device_SerialPort_PARITY_EVEN
#define com_minipos_device_SerialPort_PARITY_EVEN 2L
#undef com_minipos_device_SerialPort_DATABITS_5
#define com_minipos_device_SerialPort_DATABITS_5 5L
#undef com_minipos_device_SerialPort_DATABITS_6
#define com_minipos_device_SerialPort_DATABITS_6 6L
#undef com_minipos_device_SerialPort_DATABITS_7
#define com_minipos_device_SerialPort_DATABITS_7 7L
#undef com_minipos_device_SerialPort_DATABITS_8
#define com_minipos_device_SerialPort_DATABITS_8 8L
#undef com_minipos_device_SerialPort_STOPBITS_1
#define com_minipos_device_SerialPort_STOPBITS_1 1L
#undef com_minipos_device_SerialPort_STOPBITS_2
#define com_minipos_device_SerialPort_STOPBITS_2 2L
#undef com_minipos_device_SerialPort_STOPBITS_1_5
#define com_minipos_device_SerialPort_STOPBITS_1_5 3L
#undef com_minipos_device_SerialPort_FLOWCONTROL_NONE
#define com_minipos_device_SerialPort_FLOWCONTROL_NONE 0L
#undef com_minipos_device_SerialPort_FLOWCONTROL_RTSCTS_IN
#define com_minipos_device_SerialPort_FLOWCONTROL_RTSCTS_IN 1L
#undef com_minipos_device_SerialPort_FLOWCONTROL_RTSCTS_OUT
#define com_minipos_device_SerialPort_FLOWCONTROL_RTSCTS_OUT 2L
#undef com_minipos_device_SerialPort_FLOWCONTROL_RTSCTS
#define com_minipos_device_SerialPort_FLOWCONTROL_RTSCTS 3L
#undef com_minipos_device_SerialPort_FLOWCONTROL_XONXOFF_IN
#define com_minipos_device_SerialPort_FLOWCONTROL_XONXOFF_IN 4L
#undef com_minipos_device_SerialPort_FLOWCONTROL_XONXOFF_OUT
#define com_minipos_device_SerialPort_FLOWCONTROL_XONXOFF_OUT 8L
#undef com_minipos_device_SerialPort_FLOWCONTROL_XONXOFF
#define com_minipos_device_SerialPort_FLOWCONTROL_XONXOFF 12L
/*
 * Class:     com_minipos_device_SerialPort
 * Method:    createFileDescriptor
 * Signature: (I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_minipos_device_SerialPort_createFileDescriptor
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_minipos_device_SerialPort
 * Method:    closeSerialPort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_minipos_device_SerialPort_closeSerialPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_minipos_device_SerialPort
 * Method:    openSerialPort
 * Signature: (Ljava/lang/String;IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_minipos_device_SerialPort_openSerialPort
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
